{{- if .Values.provisioning.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-provisioning-secret
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioning
type: Opaque
stringData:
  {{- if .Values.provisioning.env.POSTGRES_ADMIN_URL }}
  POSTGRES_ADMIN_URL: {{ .Values.provisioning.env.POSTGRES_ADMIN_URL | quote }}
  {{- end }}
  {{- if .Values.provisioning.env.VAULT_TOKEN }}
  VAULT_TOKEN: {{ .Values.provisioning.env.VAULT_TOKEN | quote }}
  {{- end }}
  {{- if .Values.provisioning.env.GIT_AUTH_TOKEN }}
  GIT_AUTH_TOKEN: {{ .Values.provisioning.env.GIT_AUTH_TOKEN | quote }}
  {{- end }}
  {{- if .Values.provisioning.env.ARGOCD_AUTH_TOKEN }}
  ARGOCD_AUTH_TOKEN: {{ .Values.provisioning.env.ARGOCD_AUTH_TOKEN | quote }}
  {{- end }}
{{- end }}
