{{- if .Values.backend.env.DATABASE_URL }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.fullname" . }}-backend-secret
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  {{- if .Values.backend.env.KEYCLOAK_ADMIN_CLIENT_SECRET }}
  KEYCLOAK_ADMIN_CLIENT_SECRET: {{ .Values.backend.env.KEYCLOAK_ADMIN_CLIENT_SECRET | quote }}
  {{- end }}
{{- end }}
