{{- if .Values.provisioning.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-provisioning
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioning
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.provisioning.service.port }}
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: provisioning
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
