apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: postgres
data:
  POSTGRES_DB: "<path:k8s-stack/data/runtime_edc/postgres#postgres-db>"
  POSTGRES_PASSWORD: "<path:k8s-stack/data/runtime_edc/postgres#postgres-admin-password>"
  POSTGRES_USER: "<path:k8s-stack/data/runtime_edc/postgres#postgres-admin-user>"