apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: edc-postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: 32748
  selector:
   app: postgres